### ISSUE TITLE
SSD Triage

### ISSUE THREAD

**Issue by Manssur94** [Manssur94/Manssur-Personal-Tasks#182]

**Comment by Manssur94** [comment]
Needs to be assigned: 

- ~Evaluate Alternatives for MPA Slack Support Due to High Frontline Utilization
[#1692](https://github.com/Shopify/psn/issues/1692) | Created: 12 Aug | Priority P1~
- ~Review and Reassign Physical Mail Support Responsibilities
[#1415](https://github.com/Shopify/psn/issues/1415) | Created Jun 11 | Priority Low~
- [Workflow] Do we still need a separate CSV queue for core?
[#1603](https://github.com/Shopify/psn/issues/1603) | Created Jul 26 | Priority Low
- ~Guru Card Updates: Discouraging Advisors From Providing AI-Generated Code
[#1679](https://github.com/Shopify/psn/issues/1679) | Created: Aug 9 | Priority Low~
- ~[Verdant] Help improve Verdant config in existing engineering Slack channel(s)
[#1670](https://github.com/Shopify/psn/issues/1670) | Created Aug 8 | Priority Medium~

**Comment by Manssur94** [comment]
Aug 14 
- [x] Update Issue: Evaluate Alternatives for MPA Slack Support Due to High Frontline Utilization #1692
- [x] Check in with Eva to see if there is an update #support-ssa Helper Bot advising Incorrectly [#1676](https://github.com/Shopify/psn/issues/1676)
- [x] Add comment to check on this next week due absence of leads 1099-k Payment Forms Improvement Proposal [#1014](https://github.com/Shopify/psn/issues/1014)
- [x] Add comment to check on this next week due absence of leads Need Admin Flow for Self-Serve Domain Renewals to Reduce Redemption Escalations [#594](https://github.com/Shopify/psn/issues/594)
